amzn/smoke-aws-generate

Package.resolved
Package.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientModelErrorsDelegate.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/AWSModelErrorsDelegate.swift

*Description of changes:* Conform to the updated ModelErrorsDelegate protocol.

Conform to the updated ModelErrorsDelegate protocol.

---

Sources/SmokeAWSGenerate/RDSDataConfiguration.swift
Sources/SmokeAWSGenerate/main.swift

*Issue #, if available: https://github.com/amzn/smoke-aws/issues/20
- Added RDSDataConfiguration as part of the tasks to support RDS-Data API on smoke-aws.

Add RDSDataConfiguration

---

.gitignore
.travis.yml
CITests/run
Package.resolved
Package.swift
README.md
Sources/APIGatewayClientModelGenerate/APIGatewayClientModelErrorsDelegate.swift
Sources/APIGatewayClientModelGenerate/ServiceModelCodeGeneration+generateServerApplicationFiles.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientQueryOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSModelErrorsDelegate.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+commonAWSFunctions.swift
Sources/SmokeAWSModelGenerate/SmokeAWSModelGenerate.swift

*Description of changes:* Smoke http 2 compatible generation

Smoke http 2 compatible generation

---

Package.resolved
Package.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientModelErrorsDelegate.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSModelErrorsDelegate.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

*Description of changes:* Add support for SmokeFramework 2 generation.

Add support for SmokeFramework 2 generation.

---

Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientQueryOperationBody.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientDeinitializer.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

Async http client

---

.travis.yml
CITests/run
README.md

*Description of changes:* Fix CI tests.

Fix CI tests.

---

.travis.yml
Package.resolved
Package.swift
README.md

*Description of changes:* Add Swift 5.2 CI tests.

Add Swift 5.2 CI tests.

---

Package.resolved
Package.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+commonAWSFunctions.swift

Update SmokeHTTP dependency.

---

Package.resolved
Package.swift
Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Update to beta 1 dependencies.

Update to beta 1 dependencies.

---

Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

Support non tls calls

---

Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientDeinitializer.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+commonAWSFunctions.swift

*Description of changes:* Clients to only close httpclients if they created them.

Clients to only close httpclients if they created them.

---

Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientModelErrorsDelegate.swift
Sources/APIGatewayClientModelGenerate/ServiceModelCodeGeneration+generateServerApplicationFiles.swift

*Description of changes:* Update APIGateway client generation.

Update APIGateway client generation.

---

Package.resolved
Package.swift
Sources/SmokeAWSGenerate/CloudFormationConfiguration.swift
Sources/SmokeAWSGenerate/CloudwatchConfiguration.swift
Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Add generation for Cloudformation model and client.

Add generation for Cloudformation model and client.

---

.travis.yml
CITests/run
README.md
Sources/APIGatewayClientModelGenerate/ServiceModelCodeGeneration+generateServerApplicationFiles.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

*Description of changes:* Code generation changes for retry behaviour improvements.

Code generation changes for retry behaviour improvements.

---

Package.resolved
Sources/APIGatewayClientGenerate/main.swift
Sources/APIGatewayClientModelGenerate/ServiceModelCodeGeneration+generateServerApplicationFiles.swift
Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Update smoke-aws version requirement.

Update smoke-aws version requirement.

---

Package.resolved
Package.swift
Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Add SmokeAWSMetrics package.

Add SmokeAWSMetrics package.

---

Sources/CoralToJSONServiceModel/Metadata.swift
Sources/SmokeAWSGenerate/CodeBuildConfiguration.swift
Sources/SmokeAWSGenerate/CodePipelineConfiguration.swift
Sources/SmokeAWSGenerate/ECRConfiguration.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/CoralToJSONServiceModel+getAWSClientAttributes.swift

*Description of changes:* Add ecr client.

Add ecr client.

---

Package.resolved
Package.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift

*Description of changes:* Make various properties public.

Make various properties public.

---

.travis.yml
Package.resolved
Package.swift
README.md
Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Modernize dependencies
1. Use apple/swift-argument-parser for SmokeAWSGenerate command.

Modernize dependencies

---

Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientQueryOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

*Description of changes:* Generate EventLoopFuture returning APIs only.

Generate EventLoopFuture returning APIs only.

---

Package.resolved
Sources/APIGatewayClientGenerate/main.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/SmokeAWSModelGenerate.swift

*Description of changes:* Remove return value warning.

Remove return value warning.

---

Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Add _SmokeHTTPClientConcurrency package for experimental async/await APIs.

Add _SmokeHTTPClientConcurrency package

---

.travis.yml
Package.resolved
README.md
Sources/APIGatewayClientGenerate/main.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientQueryOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift
Sources/SmokeAWSModelGenerate/SmokeAWSModelGenerate.swift

*Description of changes:* Async await client apis

Async await client apis

---

Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift

*Description of changes:* Use correct call prefix for api gateway client.

Use correct call prefix for api gateway client.

---

.travis.yml
README.md
Sources/APIGatewayClientModelGenerate/ServiceModelCodeGeneration+generateServerApplicationFiles.swift
Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Generate 1.38.57 models

Generate 1.38.57 models

---

.travis.yml
Package.resolved
README.md
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift

*Description of changes:* Fix indentation remove legacy manifest file generation.

Fix indentation remove legacy manifest file generation.

---

Package.resolved
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate.swift

Conform to updated client delegate protocol introduced in [1] to allow for multi-line type descriptions.
[1] https://github.com/amzn/service-model-swift-code-generate/pull/34

Conform to updated client delegate protocol.

---

Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

*Issue #, if available:* Make stage optional for APIGateway clients as it is possible to configure custom domains not to require the stage in the path.

Make stage optional for APIGateway clients.

---

Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

*Description of changes:* Add the option to pass in the ConnectionPool configuration into clients.

Configurable connection pool

---

Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientDeinitializer.swift
Sources/SmokeAWSModelGenerate/ServiceModelCodeGenerator+generateProtocolAsyncExtensions.swift
Sources/SmokeAWSModelGenerate/SmokeAWSModelGenerate.swift

1. Add protocol async extensions.
2. Add async shutdown method for clients.

Add protocol async extensions.

---

Package.resolved
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientDeinitializer.swift

1. Add async shutdown for clients.
The same changes were made on the smoke-aws-generate-2.x branch with #51.

Add async shutdown for clients.

---

.github/workflows/swift.yml
Package.resolved
Package.swift
README.md

Update CI for Swift 5.6, removing 5.3.

Update CI for Swift 5.6, removing 5.3.

---

Sources/SmokeAWSGenerate/DynamoDBConfiguration.swift
Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Retry DynamoDB on internal server errors.

Retry DynamoDB on internal server errors.

---

Package.resolved
Package.swift

Update service-model-swift-code-generate dependency to 3.0.0-beta.5.

Update service-model-swift-code-generate dependency to 3.0.0-beta.5.

---

Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

*Description of changes:* Make initializer generator functions public.

Make initializer generator functions public.

---

Package@swift-5.4.swift
Package@swift-5.5.swift

*Description of changes:* Fix dependency issue on Swift 5.5 and 5.4.

Fix dependency issue on Swift 5.5 and 5.4.

---

Package.resolved
Package.swift
Package@swift-5.5.swift

*Description of changes:* Update swift-argument-parser dependency.

Update swift-argument-parser dependency.

---

Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration.swift

*Description of changes:* Add support for additional model path configurations. A `generateFromModel` variant with `modelFilePaths` and a variant with `modelDirectoryPaths`.

Add support for additional model path configurations.

---

Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration+generateClientApplicationFiles.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration.swift

*Description of changes:* Enable initializing package with a custom code generator.

Enable initializing package with a custom code generator.

---

Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration+generateClientApplicationFiles.swift

*Description of changes:* Fix initializer parameter name.

Fix initializer parameter name.
