amzn/smoke-aws-generate

Sources/SmokeAWSGenerate/RDSConfiguration.swift
Sources/SmokeAWSGenerate/main.swift

*Issue*: https://github.com/amzn/smoke-aws/issues/13
- Added RDSConfiguration as part of the tasks to support RDS API on [smoke-aws](https://github.com/amzn/smoke-aws/).
- Made changes by referring [DynamoDBConfiguration](https://github.com/amzn/smoke-aws-generate/blob/2f1a2136e3463a4371d5af87d5d1705aee83dcc6/Sources/SmokeAWSGenerate/DynamoDBConfiguration.swift) and [RDS API](https://github.com/aws/aws-sdk-go/tree/c4cc55674c9e5a6d4e1fcb86f3d8f7597d3980b2/models/apis/rds) on aws-sdk-go.
I'd appreciate it if you would give feedback if there is anything to be fixed.

Add RDSConfiguration

---

Sources/CoralToJSONServiceModel/Metadata.swift

*Issue: N/A
In this PR, **serviceAbbreviation** field has been changed to an optional field.
**serviceAbbreviation** is an optional field and actually there are some APIs on aws-sdk-go such as [rds-data](https://github.com/aws/aws-sdk-go/blob/c4cc55674c9e5a6d4e1fcb86f3d8f7597d3980b2/models/apis/rds-data/2018-08-01/api-2.json), [apigateway](https://github.com/aws/aws-sdk-go/tree/c4cc55674c9e5a6d4e1fcb86f3d8f7597d3980b2/models/apis/apigateway/2015-07-09) and [cloudformation](https://github.com/aws/aws-sdk-go/blob/c4cc55674c9e5a6d4e1fcb86f3d8f7597d3980b2/models/apis/cloudformation/2010-05-15/api-2.json) in which **serviceAbbreviation** is not included.
If a new configuration which does not include `serviceAbbreviation` (e.g. rds-data) is newly added without this …

Make serviceAbbreviation on Metadata an optional field

---

Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientQueryOperationBody.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift

*Description of changes:* Fixes https://github.com/amzn/smoke-aws/issues/55 by getting the correctly typed error to be thrown by by *Sync APIs.

Fix Sync APIs throw HTTPClientError rather than cause.

---

Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientAttributes.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+commonAWSFunctions.swift

*Description of changes:* Add the ability to specify the InvocationTraceContext to use by default with the generator's with(logger:) variant.

Add the ability to specify the InvocationTraceContext to use by default

---

Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift

*Description of changes:* Change access level to public for typed error extension functions.

Change access level to public for typed error extension functions.

---

Sources/SmokeAWSGenerate/CodePipelineConfiguration.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/AWSModelErrorsDelegate.swift

…ne client.
1. Don't fail decoding if JSON error type is not present. 
2. 2. Add CodePipeline client.

Don't fail decoding if JSON error type is not present. 

---

Sources/SmokeAWSGenerate/AppConfigConfiguration.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/AWSModelErrorsDelegate.swift
Sources/SmokeAWSModelGenerate/SmokeAWSModelGenerate.swift

Add code generation for AWS AppConfig client.
Allow override of model error type coding keys.
Allow client configurations to specify an HTTP header that contains the error type in an error HTTP response.

Add AWS AppConfig client

---

Sources/APIGatewayClientModelGenerate/APIGatewayClientModelErrorsDelegate.swift

*Issue #, if available:* Generate error option set as it is now used by `(ServiceName)ModelOperations.allowedErrors`

Generate error option set for APIGateway clients

---

Sources/SmokeAWSGenerate/ECSConfiguration.swift
Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Correctly generates ECS timestamps as doubles rather than strings.

Fix timestamp type for ECS.

---

Sources/APIGatewayClientModelGenerate/APIGatewayClientModelErrorsDelegate.swift
Sources/SmokeAWSModelGenerate/AWSModelErrorsDelegate.swift

*Description of changes:* Create an untypedError if there is no error type rather than failing with a deserialisation error.

Create an untypedError if there is no error type.

---

Sources/SmokeAWSGenerate/SNSConfiguration.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSCodeGenerationCustomizations.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+commonAWSFunctions.swift
Sources/SmokeAWSModelGenerate/SmokeAWSModelGenerate.swift

This is a follow up to the https://github.com/amzn/smoke-aws/pull/121
This update introduces two things:
* The package is updated to customize AWS clients content-type header
* SNS client is updated to use `FormEncodedXMLAWSHttpClientDelegate` that encodes query parameters into request body
* SNS client is updated to use `application/x-www-form-urlencoded; charset=utf-8` which goes hand-in-hand with `FormEncodedXMLAWSHttpClientDelegate`
This collectively creates an SNS client that can send messages larger than ~16KB.

Customize SNS client to support large messages

---

Package.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

This change fixes the error when using the `3.0.0-beta.7` release of `service-model-swift-code-generate`.  The error is caused by the Client Generator still using the old client name instead of the new one prefixed by `Generic`.

Use Generic Client Name with Client Generator

---

README.md
Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration+generateClientApplicationFiles.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

*Description of changes:* Streamline initialising clients from a web or service framework using the `HTTPClientInvocationAttributes`. Added an example of using these initializers to the README.

Add client initializers that accept an HTTPClientInvocationAttributes instance

---

Sources/SmokeAWSGenerate/main.swift

The last model `smoke-aws` was generated with is v1.44.60. This update sync `smoke-aws-generate` with that.
It also prints fetched model version to the terminal.
Update aws-sdk-go model tag to v1.44.60 to sync up with `smoke-aws`.
Use treeless clone to speed up aws-sdk-go model cloning.
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
> We strongly recommend that developers do not use treeless clones for their daily work. Treeless clones are really only helpful for automated builds when you want to quickly clone, compile a project, then throw away the repository. In environments like GitHub Actions using public runners, you want to minimize your clone time so you can spend your machine time actually …

Update aws-sdk-go model tag to v1.44.60

---

Sources/SmokeAWSGenerate/main.swift

Use shallow clone instead of treeless. Shallow clone is faster. In my previous PR #71 I confused blobless clone with shallow clone. 
Shallow clone is the fastest.
https://github.blog/2020-12-22-git-clone-a-data-driven-study-on-cloning-behaviors/
> Unsurprisingly, shallow clone is the fastest clone for the client, followed by a treeless then blobless partial clones, and finally full clones.
Local testing.
Treeless:
```
time git clone --branch v1.44.60 --filter=tree:0 https://github.com/aws/aws-sdk-go.git model-treeless
3.69s user 2.77s system 8% cpu 1:20.44 total
```
Shallow:
```
time git clone --branch v1.44.60 --depth=1 https://github.com/aws/aws-sdk-go.git model-depth
2.53s user 2.12s system 7% cpu 1:01.12 total
```
By submitting this …

Use shallow clone instead of treeless

---

Package.resolved
Package.swift
Package@swift-5.5.swift
Sources/APIGatewayClientInitialize/APIGatewayClientInitializeCommand.swift
Sources/APIGatewayClientInitialize/APIGatewayClientSwiftCodeGen.swift

Adds dependency on openapi-swift-code-generate for OpenAPI and Swagger 
models

Add dependency on openapi-swift-code-generate and bump service-model-swift-code-generate version

---

Sources/APIGatewayClientGenerate/APIGatewayClientGenerateCommand.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration.swift

*Description of changes:* Only depend on swift-argument-parser in the targets where it is required. Also fixes CI build failure.

Only depend on swift-argument-parser in the targets where it is required.

---

Package.resolved
Package.swift
Package@swift-5.5.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration+generateClientApplicationFiles.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift
Sources/SmokeAWSModelGenerate/SmokeAWSModelGenerate.swift

*Description of changes:* Generate clients that depend on `smoke-aws-support` rather than on `smoke-aws`. Update code to reflect contract changes in `service-model-swift-code-generate` to avoid hard-coding smoke-aws[-support] references.

Generate clients that depend on smoke-aws-support

---

Package.resolved
Package.swift
Sources/APIGatewayClientGenerate/APIGatewayClientSwiftCodeGen.swift
Sources/APIGatewayClientModelGenerate/APIGatewayClientCodeGeneration.swift
Sources/CoralToJSONServiceModel/CoralToJSONServiceModel.swift
Sources/SmokeAWSGenerate/CloudFormationConfiguration.swift
Sources/SmokeAWSGenerate/CloudwatchConfiguration.swift
Sources/SmokeAWSGenerate/CodeBuildConfiguration.swift
Sources/SmokeAWSGenerate/CodePipelineConfiguration.swift
Sources/SmokeAWSGenerate/DynamoDBConfiguration.swift
Sources/SmokeAWSGenerate/EC2Configuration.swift
Sources/SmokeAWSGenerate/ECRConfiguration.swift
Sources/SmokeAWSGenerate/ECSConfiguration.swift
Sources/SmokeAWSGenerate/RDSConfiguration.swift
Sources/SmokeAWSGenerate/RDSDataConfiguration.swift
Sources/SmokeAWSGenerate/S3Configuration.swift
Sources/SmokeAWSGenerate/SNSConfiguration.swift
Sources/SmokeAWSGenerate/SimpleQueueConfiguration.swift
Sources/SmokeAWSGenerate/SimpleWorkflowConfiguration.swift
Sources/SmokeAWSGenerate/StepFunctionsConfiguration.swift
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientQueryOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientDeinitializer.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientFileHeader.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift
Sources/SmokeAWSModelGenerate/ModelClientDelegate+commonAWSFunctions.swift
Sources/SmokeAWSModelGenerate/SmokeAWSModelGenerate.swift

*Description of changes:* Use model type specific ModelOverride types. Required due the underlying changes made in https://github.com/amzn/service-model-swift-code-generate/pull/68

Use model type specific ModelOverride types.

---

.github/workflows/swift.yml
Package.resolved
Package.swift
README.md
Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientQueryOperationBody.swift
Sources/SmokeAWSModelGenerate/ServiceModelCodeGenerator+generateProtocolAsyncExtensions.swift
Sources/SmokeAWSModelGenerate/SmokeAWSModelGenerate.swift

Adds support for Swift Concurrency based implementations in a backwards-compatible manner.
These changes only relate to the `smoke-aws-generate-2.x` branch - which is only used to generate the `smoke-aws` package result in
https://github.com/amzn/smoke-aws/compare/main...on_swift_concurrency_threads
**(baseName)ClientProtocolV2**: a new protocol that just contains Swift Concurrency (Async/Await) based APIs
**(baseName)ClientProtocol**: an existing protocol that now conforms to the new `(baseName)ClientProtocolV2` protocol. There are no other changes to this protocol.
**(baseName)ClientProtocol+async**: existing extensions to the existing `(baseName)ClientProtocol` that provide Swift Concurrency (Async/Await) based APIs by delegating to …

Add the ability to generate Swift Concurrency implementations.

---

Sources/SmokeAWSGenerate/ECRConfiguration.swift
Sources/SmokeAWSGenerate/main.swift

*Description of changes:* Correct timestamp type for ECR models. Verified timestamps from the ECR service are returned as doubles rather than longs.
For example
```
imagePushedAt":1.688712875E9
```

Correct timestamp type for ECR models

---

Package.resolved
Package.swift
Sources/SmokeAWSModelGenerate/APIGatewayClientDelegate.swift

*Description of changes:* Convert HTTPError.deserializationError into a service-specific UnmodeledError.deserializationError for additional context.

Convert HTTPError.deserializationError into a service-specific one

---

Sources/SmokeAWSModelGenerate/ModelClientDelegate+addAWSClientInitializer.swift

*Description of changes:* Allows the client to be correctly identified in distributed traces. Also uses the new singleton EventLoop rather than creating a new one (which is deprecated by swift-nio).

Specify the client name for reporting purposes.

---

Sources/SmokeAWSGenerate/main.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientOperationBody.swift
Sources/SmokeAWSModelGenerate/AWSClientDelegate+addAWSClientQueryOperationBody.swift

*Description of changes:* Use the AWSClientInvocationDelegate factory function for structured concurrency implementations. This will construct the AWSClientInvocationDelegate instance appropriately for the credentials provider instance passed, using credentials from the `CredentialsProviderV2` if available.

Use the AWSClientInvocationDelegate factory function

---

Sources/SmokeAWSGenerate/CloudwatchConfiguration.swift

URL encoded requests do not support as much as data as POST body. This will allow client to send up to 1MB of data to CloudWatch service.
This update to the client changes where the payload is placed in the HTTP request. Currently it's in the URL. After this change it will be in POST body.
*Testing:*
Before (URL encoded):
```
2024-01-25T13:23:46-0500 trace cw : outgoingEndpoint=https://monitoring.us-west-2.amazonaws.com:443/%3FAction=PutMetricData&MetricData.member.1.MetricName=TestMetric&MetricData.member.1.Value=1.0&Namespace=TestNamespace&Version=2010-08-01 outgoingRequestId=883B59FB-E594-4642-8650-38AED81DDDAE [SmokeHTTPClient] Sending POST request to endpoint: https://monitoring.us-west-2.amazonaws.com:443/?Action=PutMetricData&Metric …
```

Update CloudWatch client to send payload in POST body instead of URL

---

Package.resolved
Package.swift

Update SwaggerParser repository location because original is 404
Updated SwaggerParser to use a fork.
openapi-swift-code-generate 1.0.3 -> SwaggerParser

Update SwaggerParser repository location because original is 404
